import {motion} from 'motion/react';
import {workdaySchedule,type WorkdayRun} from '@/lib/workday';
export default function WorkdayScreen({run,onEnter,onReset,onNewEmployee}:{run:WorkdayRun;onEnter:()=>void;onReset:()=>void;onNewEmployee:()=>void}){
 const complete=run.status==='prototype-complete';const failed=run.status==='failed';
 if(failed)return <motion.section key="failed-workday" className="failed-workday"><div className="termination-form"><span className="document-code">HR / SHIFT TERMINATION / {run.currentTime}</span><div className="termination-stamp">SHIFT<br/>TERMINATED</div><h1>YOU DID NOT<br/>SURVIVE THE<br/>MORNING STANDUP.</h1><div className="failed-capacity"><span>MENTAL CAPACITY</span><strong>0 / 100</strong></div><p>Your access badge still works. This appears to be an oversight.</p><button className="primary-button" onClick={onReset}>CLOCK IN AGAIN <span>↗</span></button><button className="text-button" onClick={onNewEmployee}>NEW EMPLOYEE</button></div></motion.section>;
 return <motion.section key="workday" className="workday-screen">
  <div className="workday-heading"><div><span className="eyebrow">INTERNAL OPERATIONS / SHIFT 001</span><h1>YOUR<br/>WORKDAY</h1><p>SURVIVE UNTIL <strong>17:00</strong>. Then clock out like nothing happened.</p></div><div className="run-clock"><span>CURRENT TIME</span><strong>{run.currentTime}</strong><small>{complete?'STILL EMPLOYED':'SHIFT IN PROGRESS'}</small></div></div>
  <div className="workday-grid"><aside className="employee-condition"><span className="document-code">EMPLOYEE CONDITION REPORT</span><h2>{run.fighter.name}</h2><p>{run.fighter.profession} / {run.fighter.style} class</p><div className="run-health"><span>MENTAL CAPACITY</span><strong>{run.mentalCapacity} / 100</strong><i><b style={{width:`${run.mentalCapacity}%`}}/></i></div><small>Damage carries through the workday.<br/>Occupational health was unavailable.</small></aside>
   <div className="schedule-sheet"><div className="schedule-title"><span>TODAY</span><small>AGENDA SUBJECT TO UNREASONABLE CHANGE</small></div><ol>{workdaySchedule.map(entry=>{const done=entry.id==='clock-in'||(entry.id==='scrum-lord'&&complete);const current=entry.id==='scrum-lord'&&!complete;const locked=!done&&!current;return <li key={entry.id} className={`${done?'schedule-done':''} ${current?'schedule-current':''} ${locked?'schedule-locked':''}`}><time>{entry.time}</time><span className="schedule-mark">{done?'✓':current?'!':'—'}</span><div><strong>{entry.title}</strong><small>{entry.detail}</small></div>{current&&<button onClick={onEnter}>ENTER MEETING →</button>}</li>})}</ol></div>
   <aside className={`encounter-brief ${complete?'brief-complete':''}`}>{complete?<><span className="document-code">MEETING OUTCOME / FILED 09:47</span><div className="cancelled-stamp">MEETING SURVIVED</div><h2>ONE MEETING DOWN.</h2><p>Several regrettable calendar events remain.</p><div className="up-next"><span>11:15 / UP NEXT</span><strong>IDENTITY REDACTED</strong><small>Threat assessment pending.</small></div><div className="prototype-end"><strong>WORKDAY PROTOTYPE ENDS HERE</strong><p>You survived until 09:47.<br/>Eventually you’ll need to make it to 17:00.</p></div><button className="primary-button" onClick={onReset}>CLOCK IN AGAIN <span>↗</span></button><button className="text-button" onClick={onNewEmployee}>NEW EMPLOYEE</button></>:<><span className="document-code">CALENDAR EVENT / 09:30</span><span className="brief-kicker">FIRST PROBLEM OF THE DAY</span><h2>THE<br/>SCRUM LORD</h2><dl><div><dt>CLASS</dt><dd>MANAGEMENT</dd></div><div><dt>THREAT</dt><dd>MEETINGS</dd></div><div><dt>WEAKNESS</dt><dd>ACTUAL WORK</dd></div><div><dt>DURATION</dt><dd>15 MIN*</dd></div></dl><p>Your calendar says 15 minutes.<br/>Nobody believes it.</p><small>*Estimated duration not legally binding.</small><button className="primary-button" onClick={onEnter}>ENTER MEETING <span>↗</span></button></>}</aside>
  </div>
 </motion.section>;
}
